In [1]:
import numpy

In [2]:
array1 = numpy.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [3]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [15]:
type(array1)

numpy.ndarray

**ndarray = n차원 배열** (11, ) 이렇게 나온 이유

In [5]:
array1.shape

(11,)

In [9]:
array2 = numpy.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [11]:
type(array2)

numpy.ndarray

In [13]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
array2.shape

(3, 4)

In [18]:
array1.size

11

In [20]:
array2.size

12

☝  __행과 열을 곱한게 행렬의 사이즈가 된다.__

In [23]:
array3 = numpy.full(6, 7)

In [26]:
print(array3)

[7 7 7 7 7 7]


### 모든 값이 0인 numpy array 생성

In [28]:
arr1 = numpy.full(6, 0)
arr2 = numpy.zeros(6, dtype=int)

print(arr1)
print(arr2)

[0 0 0 0 0 0]
[0 0 0 0 0 0]


### 모든 값이 1인 numpy array 생성

In [31]:
arr3 = numpy.full(6, 1)
arr4 = numpy.ones(6, dtype=int)

print(arr3)
print(arr4)

[1 1 1 1 1 1]
[1 1 1 1 1 1]


## 랜덤한 값들로 생성

### numpy의 random 모듈의 random 함수를 사용하는 절차
__numpy.random.random__

In [33]:
a1 = numpy.random.random(6)
a2 = numpy.random.random(6)

print(a1)
print(a2)

[0.89682556 0.99376694 0.0929521  0.08102704 0.20579846 0.66130563]
[0.58962963 0.50120545 0.62269732 0.00786178 0.16877883 0.24044907]


## 연속된 값드리 담긴 numpy array 생성

__파이썬의 range 함수와 비슷하게 사용(파라미터가 1개, 2개, 3개)__

### 파라미터 1개

In [35]:
a = numpy.arange(6)
print(a)

[0 1 2 3 4 5]


### 파라미터 2개

In [38]:
b = numpy.arange(1, 7)
print(b)

[1 2 3 4 5 6]


### 파라미터 3개

In [39]:
c = numpy.arange(2, 9, 3)
print(c)

[2 5 8]
