In [2]:
import numpy as np

In [4]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [6]:
array1[0]

2

In [9]:
array1[2]

5

In [11]:
array1[-1]

31

In [13]:
array1[[1, 3, 4]]

array([ 3,  7, 11])

In [15]:
array2 = np.array([2, 1, 3])

In [17]:
array1[array2]

array([5, 3, 7])

In [19]:
array1[2:7]

array([ 5,  7, 11, 13, 17])

In [21]:
array1[:7]

array([ 2,  3,  5,  7, 11, 13, 17])

In [22]:
array1[2:11:2]

array([ 5, 11, 17, 23, 31])