In [2]:
import numpy as np

In [4]:
array1 = np.arange(10)
array2 = np.arange(10,20)

In [6]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
array1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
array1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [12]:
array1 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

**저장시키지는 않아서 array1의 원래 값들은 array1에 남아있다.**

In [13]:
array1 + array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [14]:
array1 * array2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [17]:
array1 / array2

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

## Numpy 불린 연산



In [18]:
array3 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [19]:
array3 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [20]:
array3 % 2 == 0

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [23]:
booleans = np.array([True, True, False, True, True, False, True, True, True, False, False, True])

In [25]:
np.where(booleans)

(array([ 0,  1,  3,  4,  6,  7,  8, 11], dtype=int64),)

In [26]:
array3 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [27]:
np.where(array3 > 4)

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [28]:
filter = np.where(array3 > 4)
filter

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [30]:
array3[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

# Numpy 기본 통계

## 최댓값, 최솟값

**max 메소드와 min 메소드를 사용**

In [32]:
m_array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(m_array1.max())
print(m_array1.min())

31
5


## 평균값

**mean 메소드를 사용 = 평균값 구하기**

In [36]:
a_array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(a_array1.mean())

15.25


## 중앙값

**median 메소드를 사용하면 중간값을 구함.** (특이한 점은 median은 numpy array의 메소드가 아니라 numpy의 메소드이다.)

In [38]:
d_array1 = np.array([8, 12, 9, 15, 16])
d_array2 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(np.median(d_array1))
print(np.median(d_array2))

12.0
13.5


## 표준편차, 분산

**std 메소드는 표준편차, var 메소드는 분산**

In [39]:
s_array = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(s_array.std())
print(s_array.var())

8.496322733983215
72.1875
